# Generated by Django 4.2.9 on 2024-01-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.FileField(upload_to="skill_assess/static/resumes"),
                ),
                ("round_type", models.TextField()),
                ("job_title", models.TextField()),
                ("job_description", models.TextField()),
            ],
        ),
    ]
