# Generated by Django 4.2.9 on 2024-01-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=255)),
                ("round_type", models.CharField(max_length=50)),
                ("job_title", models.CharField(max_length=100)),
                ("job_description", models.TextField()),
            ],
        ),
    ]
