# Generated by Django 4.2.9 on 2024-01-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="file_path",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
