# Generated by Django 4.2.9 on 2024-01-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_resume_file_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="Res",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.FileField(upload_to="uploads/")),
                ("round_type", models.CharField(max_length=50)),
                ("job_title", models.CharField(max_length=100)),
                ("job_description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Resume",
        ),
    ]
